version: '3.8'

networks:
  memoki-network:
    driver: bridge

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: memoki-api
    ports:
      - "9090:9090"
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/memokidb
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
    networks:
      - memoki-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - memoki-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - memoki-network
    healthcheck:
      test: echo 'PING' | redis-cli
      interval: 30s
      timeout: 10s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - memoki-network

volumes:
  mongodb_data:
